# Deployment workflow - build and redeploy website on pushes to repo
name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false
    # Build Website
      - name: Build
        run: |
          npm run deploy