name: Streak

# run once a week on saturday
on:
  schedule:
    - cron: "0 0 * * 6"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Build
        run: |
          ./streaktaker /public/images/streak.svg
      - name: Commit Changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: ablades
          author_email: audaris@gmail.com
          message: "cron streak auto update: `date`"
          add: "."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
