name: Streak

on:
    schedule:
        - cron: "0 0 * * 1"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        # check out repo to github_workspace
        - uses: actions/checkout@v2

        #fetch latest streak
        - name: Fetch Streak
        run: ./streaktaker

        name: Build and Deploy
        on: [push]
        jobs:
            build-and-deploy:
            runs-on: ubuntu-latest
            steps:
                - name: Checkout 🛎️
                uses: actions/checkout@v2
                with:
                    persist-credentials: false
        
                - name: Install and Deploy
                run: |
                    npm run deploy
            