name: Streak Update
# run once a week on saturday
on:
  push:
    branches:
      - master
  schedule:
    - cron: '3 * * * *'
jobs:
  build:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Build
        run: |
          ./streaktaker /public/images/streak.svg
          echo "::set-output name=ydate::$(date -d "yesterday 22:0" +'%Y-%m-%d')"  # add :: before set-ouput
      - name: Commit Changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: ablades
          author_email: audaris@gmail.com
          message: "cron streak auto update: ${{ steps.ydate.outputs.ydate }}'"
          add: "."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
